name: infra-risk

channels:
    - conda-forge

dependencies:
        - python=3.13
        - numpy
        - geopandas
        - rasterio
        - matplotlib
        - tqdm
        - pip
        - jupyterlab
        - pyproj
        - xarray
        - rioxarray 
        - seaborn
        - pip:
            - damagescanner
            - exactextract
            - contextily
            - openpyxl 
            - pyarrow
            - lonboard
